/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DiemTamDAO;
import dao.SQLServerProvider;
import dao.ThucUongDAO;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Ban;
import pojo.DiemTam;
import pojo.HoaDon;
import pojo.Kho;
import pojo.NhanVien;
import pojo.ThucUong;

/**
 *
 * @author Nhan
 */
public class QuanLy_CaPhe extends javax.swing.JFrame {

    /**
     * Creates new form QuanLy_CaPhe
     */
    Statement stament;
    ResultSet rs;
    SQLServerProvider provider;
    DefaultTableModel model;
    
    ArrayList<NhanVien> dsNV;
    ArrayList<ThucUong> dsTU;
    ArrayList<DiemTam> dsDT;
    ArrayList<HoaDon> dsHD;
    ArrayList<Kho> dsNL;
    ArrayList<Ban> dsB;
    
    public QuanLy_CaPhe() {
        initComponents();
        this.setTitle("Quản Lý Cà Phê");
        this.setSize(600,500);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setResizable(false);
        // LOad thức uôg
        model= new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Tên thức uống");
        model.addColumn("Số lượng");
        model.addColumn("Tình trạng");
        model.addColumn("Đơn giá");
        tbTU.setModel(model);
        loadTU();
        // load điểm tâm
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Tên món");
        model.addColumn("Số lượng");
        model.addColumn("Tình trạng");
        model.addColumn("Đơn giá");
        tbDT.setModel(model);
        loadDT();
    }
    public void loadTU()
    {
        DefaultTableModel dtm = new DefaultTableModel();
        dsTU = ThucUongDAO.layDsTU();
        dtm.setRowCount(0);
        tbTU.setModel(dtm);
        for(ThucUong tu : dsTU)
        {
            String mtu = tu.getMaTU();
            String tentu= tu.getTenTU();
            int soluong = tu.getSoLuong();
            int dongia = tu.getDonGia();
            String tinhtrang = tu.getTinhTrang();
            String []thucuong ={mtu,tentu,""+soluong,tinhtrang,""+dongia};
            model.addRow(thucuong);
        }
        tbTU.setModel(model);
    }
    public void loadDT()
    {
        DefaultTableModel dtm = new DefaultTableModel();
        dsDT = DiemTamDAO.layDsDiemTam();
        dtm.setRowCount(0);
        tbDT.setModel(dtm);
        for(DiemTam dt : dsDT)
        {
            String mdt = dt.getMaDT();
            String tendt= dt.getTenDT();
            int soluong = dt.getSoLuong();
            int dongia = dt.getDonGia();
            String tinhtrang = dt.getTinhTrang();
            String []diemtam ={mdt,tendt,""+soluong,tinhtrang,""+dongia};
            model.addRow(diemtam);
        }
        tbDT.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnDrinks = new javax.swing.JPanel();
        pnTU = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTU = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDd = new javax.swing.JTextField();
        txtNamed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSLd = new javax.swing.JTextField();
        txtDGd = new javax.swing.JTextField();
        lbTTd = new javax.swing.JLabel();
        btnAddD = new javax.swing.JButton();
        btnDeld = new javax.swing.JButton();
        btnUpdD = new javax.swing.JButton();
        btnFindD = new javax.swing.JButton();
        pnDT = new javax.swing.JPanel();
        pnDoAn = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDT = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIDT = new javax.swing.JTextField();
        txtNameDT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSLDT = new javax.swing.JTextField();
        txtDGDT = new javax.swing.JTextField();
        lbDT = new javax.swing.JLabel();
        btnAddD1 = new javax.swing.JButton();
        btnDeld1 = new javax.swing.JButton();
        btnUpdD1 = new javax.swing.JButton();
        btnFindD1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mNu = new javax.swing.JMenu();
        Menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbTU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTUMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbTUMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbTU);

        javax.swing.GroupLayout pnTULayout = new javax.swing.GroupLayout(pnTU);
        pnTU.setLayout(pnTULayout);
        pnTULayout.setHorizontalGroup(
            pnTULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        pnTULayout.setVerticalGroup(
            pnTULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tên :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Số lượng:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Đơn giá:");

        lbTTd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btnAddD.setText("Thêm");
        btnAddD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDActionPerformed(evt);
            }
        });

        btnDeld.setText("Xóa");
        btnDeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeldActionPerformed(evt);
            }
        });

        btnUpdD.setText("Sửa");
        btnUpdD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdDActionPerformed(evt);
            }
        });

        btnFindD.setText("Tìm Kiếm");
        btnFindD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDrinksLayout = new javax.swing.GroupLayout(pnDrinks);
        pnDrinks.setLayout(pnDrinksLayout);
        pnDrinksLayout.setHorizontalGroup(
            pnDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnDrinksLayout.createSequentialGroup()
                .addGroup(pnDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDrinksLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(lbTTd, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDrinksLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDrinksLayout.createSequentialGroup()
                                .addGroup(pnDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIDd)
                                    .addComponent(txtNamed, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSLd)
                                    .addComponent(txtDGd, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                            .addGroup(pnDrinksLayout.createSequentialGroup()
                                .addComponent(btnAddD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeld, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFindD)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnDrinksLayout.setVerticalGroup(
            pnDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDrinksLayout.createSequentialGroup()
                .addComponent(pnTU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSLd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDGd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbTTd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddD)
                    .addComponent(btnDeld)
                    .addComponent(btnUpdD)
                    .addComponent(btnFindD))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Đồ Uống", pnDrinks);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbDT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDTMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbDTMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbDT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ID:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tên :");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Số lượng:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Đơn giá:");

        lbDT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btnAddD1.setText("Thêm");
        btnAddD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddD1ActionPerformed(evt);
            }
        });

        btnDeld1.setText("Xóa");
        btnDeld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeld1ActionPerformed(evt);
            }
        });

        btnUpdD1.setText("Sửa");
        btnUpdD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdD1ActionPerformed(evt);
            }
        });

        btnFindD1.setText("Tìm Kiếm");
        btnFindD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindD1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDoAnLayout = new javax.swing.GroupLayout(pnDoAn);
        pnDoAn.setLayout(pnDoAnLayout);
        pnDoAnLayout.setHorizontalGroup(
            pnDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnDoAnLayout.createSequentialGroup()
                .addGroup(pnDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDoAnLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(lbDT, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDoAnLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDoAnLayout.createSequentialGroup()
                                .addGroup(pnDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIDT)
                                    .addComponent(txtNameDT, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSLDT)
                                    .addComponent(txtDGDT, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                            .addGroup(pnDoAnLayout.createSequentialGroup()
                                .addComponent(btnAddD1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeld1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdD1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFindD1)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnDoAnLayout.setVerticalGroup(
            pnDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDoAnLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSLDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNameDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDGDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddD1)
                    .addComponent(btnDeld1)
                    .addComponent(btnUpdD1)
                    .addComponent(btnFindD1))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnDTLayout = new javax.swing.GroupLayout(pnDT);
        pnDT.setLayout(pnDTLayout);
        pnDTLayout.setHorizontalGroup(
            pnDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
            .addGroup(pnDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnDTLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnDoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnDTLayout.setVerticalGroup(
            pnDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
            .addGroup(pnDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnDTLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnDoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Điểm Tâm", pnDT);

        mNu.setText("File");

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        mNu.add(Menu);

        jMenuBar1.add(mNu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuActionPerformed

    private void btnFindDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindDActionPerformed
        // TODO add your handling code here:
        TimKiemThucUong dialogFind = new TimKiemThucUong(this, true);
        dialogFind.setVisible(true);
    }//GEN-LAST:event_btnFindDActionPerformed

    private void btnUpdDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdDActionPerformed
        // TODO add your handling code here:
        try {
            String maTU = txtIDd.getText();
            DefaultTableModel selectedM = (DefaultTableModel) tbTU.getModel();
            boolean like = false;
            for (int i=0;i<selectedM.getRowCount();i++)
            {
                if(maTU.equalsIgnoreCase(selectedM.getValueAt(i, 0).toString()))
                {
                    like = true;
                }
            }
            if(like == false)
            {
                JOptionPane.showMessageDialog(null, "Mã Thức uống không có trong ds , không thể update, vui lòng thêm thức uống");
                return;
            }
            ThucUong upTU = new ThucUong();
            upTU.setMaTU(txtIDd.getText());
            upTU.setTenTU(txtNamed.getText());
            upTU.setSoLuong(Integer.parseInt(txtSLd.getText()));
            upTU.setDonGia(Integer.parseInt(txtDGd.getText()));
            boolean kq = ThucUongDAO.updateTU(upTU);
            if(kq)
            JOptionPane.showMessageDialog(null, "UPDATE THÀNH CÔNG");
            else
            JOptionPane.showMessageDialog(null, "UPDATE KHÔNG THÀNH CÔNG");
            model.setRowCount(0);
            tbTU.setModel(model);
            loadTU();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnUpdDActionPerformed

    private void btnDeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeldActionPerformed
        // TODO add your handling code here:
        ThucUong delTU = new ThucUong();
        delTU.setMaTU(txtIDd.getText());
        delTU.setTenTU(txtNamed.getText());
        delTU.setSoLuong(Integer.parseInt(txtSLd.getText()));
        delTU.setDonGia(Integer.parseInt(txtDGd.getText()));
        boolean kq = ThucUongDAO.xoaTU(delTU);
        if(kq)
        JOptionPane.showMessageDialog(null, "XÓA THÀNH CÔNG");
        else
        JOptionPane.showMessageDialog(null, "XÓA KHÔNG THÀNH CÔNG");
        model.setRowCount(0);
        tbTU.setModel(model);
        loadTU();
    }//GEN-LAST:event_btnDeldActionPerformed

    private void btnAddDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDActionPerformed
        // TODO add your handling code here:
        ThucUong addTU = new ThucUong();
        addTU.setMaTU(txtIDd.getText());
        addTU.setTenTU(txtNamed.getText());
        addTU.setSoLuong(Integer.parseInt(txtSLd.getText()));
        addTU.setDonGia(Integer.parseInt(txtDGd.getText()));
        boolean kq = ThucUongDAO.themTU(addTU);
        if(kq)
        JOptionPane.showMessageDialog(null, "THÊM THÀNH CÔNG");
        else
        JOptionPane.showMessageDialog(null, "THÊM KHÔNG THÀNH CÔNG");
        model.setRowCount(0);
        tbTU.setModel(model);
        loadTU();
    }//GEN-LAST:event_btnAddDActionPerformed

    private void tbTUMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTUMouseReleased
        // TODO add your handling code here:
        if(tbTU.isEditing())
        {
            int r = tbTU.getSelectedRow();
            int c = tbTU.getSelectedColumn();
            tbTU.getCellEditor(r, c).cancelCellEditing();
        }
    }//GEN-LAST:event_tbTUMouseReleased

    private void tbTUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTUMouseClicked
        // TODO add your handling code here:

        try {

            int index = tbTU.getSelectedRow();
            DefaultTableModel selectedM = (DefaultTableModel) tbTU.getModel();
            txtIDd.setText(selectedM.getValueAt(index, 0).toString());
            txtNamed.setText(selectedM.getValueAt(index, 1).toString());
            txtSLd.setText(selectedM.getValueAt(index, 2).toString());
            txtDGd.setText(selectedM.getValueAt(index, 4).toString());
            if(selectedM.getValueAt(index,3).toString().equalsIgnoreCase("Con"))
            lbTTd.setText("MẶT HÀNG CÒN");
            else
            lbTTd.setText("MẶT HÀNG KHÔNG CÒN");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_tbTUMouseClicked

    private void tbDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDTMouseClicked
        // TODO add your handling code here:
        try{
            int index = tbDT.getSelectedRow();
            DefaultTableModel selectedM = (DefaultTableModel) tbDT.getModel();
            txtIDT.setText(selectedM.getValueAt(index, 0).toString());
            txtNameDT.setText(selectedM.getValueAt(index, 1).toString());
            txtSLDT.setText(selectedM.getValueAt(index, 2).toString());
            txtDGDT.setText(selectedM.getValueAt(index, 4).toString());
            if(selectedM.getValueAt(index,3).toString().equalsIgnoreCase("Con"))
            lbDT.setText("MẶT HÀNG CÒN");
            else
            lbDT.setText("MẶT HÀNG KHÔNG CÒN");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_tbDTMouseClicked

    private void tbDTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDTMouseReleased
        // TODO add your handling code here:
        if(tbDT.isEditing())
        {
            int r = tbDT.getSelectedRow();
            int c = tbDT.getSelectedColumn();
            tbDT.getCellEditor(r, c).cancelCellEditing();
        }
        
    }//GEN-LAST:event_tbDTMouseReleased

    private void btnAddD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddD1ActionPerformed
        // TODO add your handling code here:
        DiemTam addDT = new DiemTam();
        addDT.setMaDT(txtIDT.getText());
        addDT.setTenDT(txtNameDT.getText());
        addDT.setSoLuong(Integer.parseInt(txtSLDT.getText()));
        addDT.setDonGia(Integer.parseInt(txtDGDT.getText()));
        boolean kq = DiemTamDAO.themDT(addDT);
        if(kq)
        JOptionPane.showMessageDialog(null, "THÊM THÀNH CÔNG");
        else
        JOptionPane.showMessageDialog(null, "THÊM KHÔNG THÀNH CÔNG");
        model.setRowCount(0);
        tbTU.setModel(model);
        loadDT();
    }//GEN-LAST:event_btnAddD1ActionPerformed

    private void btnDeld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeld1ActionPerformed
        // TODO add your handling code here:
        try{
        DiemTam delDT = new DiemTam();
        delDT.setMaDT(txtIDT.getText());
        delDT.setTenDT(txtNameDT.getText());
        delDT.setSoLuong(Integer.parseInt(txtSLDT.getText()));
        delDT.setDonGia(Integer.parseInt(txtDGDT.getText()));
        boolean kq = DiemTamDAO.xoaDT(delDT);
        if(kq)
        JOptionPane.showMessageDialog(null, "XÓA THÀNH CÔNG");
        else
        JOptionPane.showMessageDialog(null, "XÓA KHÔNG THÀNH CÔNG");
        model.setRowCount(0);
        tbDT.setModel(model);
        loadDT();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnDeld1ActionPerformed

    private void btnUpdD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdD1ActionPerformed
        // TODO add your handling code here:
            try {
            String maDT = txtIDT.getText();
            DefaultTableModel selectedM = (DefaultTableModel) tbDT.getModel();
            boolean like = false;
            for (int i=0;i<selectedM.getRowCount();i++)
            {
                if(maDT.equalsIgnoreCase(selectedM.getValueAt(i, 0).toString()))
                {
                    like = true;
                }
            }
            if(like == false)
            {
                JOptionPane.showMessageDialog(null, "Mã Điểm Tâm không có trong ds , không thể update, vui lòng thêm điểm tâm");
                return;
            }
            DiemTam upDT = new DiemTam();
            upDT.setMaDT(txtIDT.getText());
            upDT.setTenDT(txtNameDT.getText());
            upDT.setSoLuong(Integer.parseInt(txtSLDT.getText()));
            upDT.setDonGia(Integer.parseInt(txtDGDT.getText()));
            boolean kq = DiemTamDAO.updateDT(upDT);
            if(kq)
            JOptionPane.showMessageDialog(null, "UPDATE THÀNH CÔNG");
            else
            JOptionPane.showMessageDialog(null, "UPDATE KHÔNG THÀNH CÔNG");
            model.setRowCount(0);
            tbDT.setModel(model);
            loadDT();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnUpdD1ActionPerformed

    private void btnFindD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindD1ActionPerformed
        // TODO add your handling code here:
        TimKiemDiemTam dta = new TimKiemDiemTam(this, true);
        this.dispose();
        dta.setVisible(true);
    }//GEN-LAST:event_btnFindD1ActionPerformed
    public void emptyTextD()
    {
        txtNamed.setText("");
        txtSLd.setText("");
        txtDGd.setText("");
        txtIDd.setText("");
    }
    public void emptyTextF()
    {
        txtNameDT.setText("");
        txtSLDT.setText("");
        txtIDT.setText("");
        txtDGDT.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLy_CaPhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLy_CaPhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLy_CaPhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLy_CaPhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLy_CaPhe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu;
    private javax.swing.JButton btnAddD;
    private javax.swing.JButton btnAddD1;
    private javax.swing.JButton btnDeld;
    private javax.swing.JButton btnDeld1;
    private javax.swing.JButton btnFindD;
    private javax.swing.JButton btnFindD1;
    private javax.swing.JButton btnUpdD;
    private javax.swing.JButton btnUpdD1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbDT;
    private javax.swing.JLabel lbTTd;
    private javax.swing.JMenu mNu;
    private javax.swing.JPanel pnDT;
    private javax.swing.JPanel pnDoAn;
    private javax.swing.JPanel pnDrinks;
    private javax.swing.JPanel pnTU;
    private javax.swing.JTable tbDT;
    private javax.swing.JTable tbTU;
    private javax.swing.JTextField txtDGDT;
    private javax.swing.JTextField txtDGd;
    private javax.swing.JTextField txtIDT;
    private javax.swing.JTextField txtIDd;
    private javax.swing.JTextField txtNameDT;
    private javax.swing.JTextField txtNamed;
    private javax.swing.JTextField txtSLDT;
    private javax.swing.JTextField txtSLd;
    // End of variables declaration//GEN-END:variables
}
